### ISSUE TITLE
- aimeos/aimeos-laravel[2021.10.1, ..., 2021.10.x-dev] require doctrine/dbal ~2.5 -> found doctrine/dbal[v2.5.0-BETA2,..., 2.13.8] but it conflicts with your root composer.json require (^3.1).

### ISSUE THREAD

**Issue by ibrahim-h-najjar** [doctrine/orm-benchmarking-suite#1]
Hi,

I'm having this error while installing Aimeos package to my laravel website:
- aimeos/aimeos-laravel[2021.10.1, ..., 2021.10.x-dev] require doctrine/dbal ~2.5 -> found doctrine/dbal[v2.5.0-BETA2,..., 2.13.8] but it conflicts with your root composer.json require (^3.1).

Could you please help me solve this?

**Comment by malarzm** [comment]
You have conflicting requirements between your composer.json and package(s) you require. You need to solve them
